package com.qa.MainClass;

import com.qa.JavaInterviewPrograms.AnagramStrings;
import com.qa.JavaInterviewPrograms.ArmstrongNumber;
import com.qa.JavaInterviewPrograms.ArrayShiftZeroToRight;
import com.qa.JavaInterviewPrograms.ArraysJoin;
import com.qa.JavaInterviewPrograms.BubbleSort;
import com.qa.JavaInterviewPrograms.CapitalizedStringWordCount;
import com.qa.JavaInterviewPrograms.DivideByZero;
import com.qa.JavaInterviewPrograms.DoubleMinValue;
import com.qa.JavaInterviewPrograms.DuplicateCharacterInString;
import com.qa.JavaInterviewPrograms.DuplicateElementsInArray;
import com.qa.JavaInterviewPrograms.ExecuteComments;
import com.qa.JavaInterviewPrograms.FileContentCount;
import com.qa.JavaInterviewPrograms.FileCopy;
import com.qa.JavaInterviewPrograms.FileCreate;
import com.qa.JavaInterviewPrograms.FileListSorted;
import com.qa.JavaInterviewPrograms.FileMaxWordCount;
import com.qa.JavaInterviewPrograms.FilePermissions;
import com.qa.JavaInterviewPrograms.FileRead;
import com.qa.JavaInterviewPrograms.HelloWorldWithoutSemicolon;
import com.qa.JavaInterviewPrograms.ImageFormatConversion;
import com.qa.JavaInterviewPrograms.IntegerCaching;
import com.qa.JavaInterviewPrograms.LaunchExternalApp;
import com.qa.JavaInterviewPrograms.LeaderElements;
import com.qa.JavaInterviewPrograms.LongNumberWithoutL;
import com.qa.JavaInterviewPrograms.MatrixCreation;
import com.qa.JavaInterviewPrograms.MatrixMultiplication;
import com.qa.JavaInterviewPrograms.MatrixTranspose;
import com.qa.JavaInterviewPrograms.MaxMethodParameters;
import com.qa.JavaInterviewPrograms.MissingElement;
import com.qa.JavaInterviewPrograms.NotANumberConcept;
import com.qa.JavaInterviewPrograms.OccuranceOfCharacterInString;
import com.qa.JavaInterviewPrograms.PassNullArgumentWithMethodOverloading;
import com.qa.JavaInterviewPrograms.PasswordsInCharArray;
import com.qa.JavaInterviewPrograms.PrintCountingWithoutLoop;
import com.qa.JavaInterviewPrograms.PrintCountingWithoutLoopRecursion;
import com.qa.JavaInterviewPrograms.PrintName;
import com.qa.JavaInterviewPrograms.PrintlnWorksInternally;
import com.qa.JavaInterviewPrograms.RandomNumbers;
import com.qa.JavaInterviewPrograms.RemoveSpacesFromString;
import com.qa.JavaInterviewPrograms.RepeatNumberCount;
import com.qa.JavaInterviewPrograms.ReverseNumber;
import com.qa.JavaInterviewPrograms.ReverseNumberRecursion;
import com.qa.JavaInterviewPrograms.RoundOffDouble;
import com.qa.JavaInterviewPrograms.StaticBlockConcept;
import com.qa.JavaInterviewPrograms.StaticBlockWithFinalVariable;
import com.qa.JavaInterviewPrograms.StringLength;
import com.qa.JavaInterviewPrograms.StringObjects;
import com.qa.JavaInterviewPrograms.StringToNumber;
import com.qa.JavaInterviewPrograms.SubString;
import com.qa.JavaInterviewPrograms.URLCompare;
import com.qa.JavaInterviewPrograms.ValidBinaryNumber;
import com.qa.JavaInterviewPrograms.ValidPhoneNumber;

public class MainExecutionClass {
	
	public static void main(String[] args) {

		// HelloWorldWithoutSemicolon.test();
		// PassNullArgumentWithMethodOverloading.test(null);
		// IntegerCaching.test();
		// DivideByZero.test();
		// NotANumberConcept.test();
		// StringObjects.test();
		// StaticBlockWithFinalVariable.test();
		// LongNumberWithoutL.test();
		// DoubleMinValue.test();
		// StaticBlockConcept.test();
		// PrintlnWorksInternally.test();
		// MaxMethodParameters.test();
		// PrintCountingWithoutLoop.test();
		// DuplicateElementsInArray.test();
		// DuplicateCharacterInString.test();
		// OccuranceOfCharacterInString.test();
		// ExecuteComments.test();
		// URLCompare.test();
		// MissingElement.test();
		// StringLength.test();
		// FileMaxWordCount.test();
		// FileCreate.test();
		// FileListSorted.test();
		// FileCopy.test();
		// FileRead.test();
		// FileContentCount.test();
		// RemoveSpacesFromString.test();
		// AnagramStrings.test();
		// ArraysJoin.test();
		// ArrayShiftZeroToRight.test();
		// CapitalizedStringWordCount.test();
		// SubString.test();
		// PrintCountingWithoutLoopRecursion.test();
		// PasswordsInCharArray.test();
		// ReverseNumber.test();
		// ReverseNumberRecursion.test();
		// ValidPhoneNumber.test();
		// ValidBinaryNumber.test();
		// RandomNumbers.test();
		// RepeatNumberCount.test();
		// BubbleSort.test();
		// StringToNumber.test();
		// RoundOffDouble.test();
		// LeaderElements.test();
		// PrintName.test();
		// ArmstrongNumber.test();
		// FilePermissions.test();
		// ImageFormatConversion.test();
		// LaunchExternalApp.test();
		// MatrixCreation.test();
		MatrixMultiplication.test();
		MatrixTranspose.test();
	}

}
